// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJygc8BjI17XxvSl9NJj9sm7q0R9-Xe-U',
    appId: '1:890633175383:web:f61e0bd5ebb7b218207e12',
    messagingSenderId: '890633175383',
    projectId: 'markt-108d2',
    authDomain: 'markt-108d2.firebaseapp.com',
    storageBucket: 'markt-108d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvMkIHg2qHJvCs7iRCt4Q15mO12_pQQs',
    appId: '1:890633175383:android:69124e64250e4144207e12',
    messagingSenderId: '890633175383',
    projectId: 'markt-108d2',
    storageBucket: 'markt-108d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa2CJb-z7uxtFSb1y1UiN0aek-FMa8-RU',
    appId: '1:890633175383:ios:0043c74038297273207e12',
    messagingSenderId: '890633175383',
    projectId: 'markt-108d2',
    storageBucket: 'markt-108d2.firebasestorage.app',
    iosBundleId: 'com.example.berty1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa2CJb-z7uxtFSb1y1UiN0aek-FMa8-RU',
    appId: '1:890633175383:ios:0043c74038297273207e12',
    messagingSenderId: '890633175383',
    projectId: 'markt-108d2',
    storageBucket: 'markt-108d2.firebasestorage.app',
    iosBundleId: 'com.example.berty1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJygc8BjI17XxvSl9NJj9sm7q0R9-Xe-U',
    appId: '1:890633175383:web:3880545d6c83fca6207e12',
    messagingSenderId: '890633175383',
    projectId: 'markt-108d2',
    authDomain: 'markt-108d2.firebaseapp.com',
    storageBucket: 'markt-108d2.firebasestorage.app',
  );
}
